apiVersion: v1
kind: Secret
metadata:
  name: radiology-db-secret
  namespace: default
type: Opaque
stringData:
  postgres-db: ${DB_NAME:radiologydb}
  postgres-user: ${SPRING_DATASOURCE_USERNAME:admin}
  postgres-password: ${SPRING_DATASOURCE_PASSWORD:secretpassword}
